---
- name: Define Project Root
  ansible.builtin.import_playbook: "../utilities/define_project_root.yaml"
  when: project_root is not defined

- name: Disable Online Wait
  hosts: "{{ ('reachable' not in groups and 'unreachable' not in groups) | ternary('all', 'reachable') }}"
  strategy: free
  gather_facts: false
  tasks:
    - name: Fetch local time
      ansible.builtin.shell:
        cmd: >
          systemctl mask systemd-networkd-wait-online.service
      become: true
