---
- name: Define Project Root
  ansible.builtin.import_playbook: "../utilities/define_project_root.yaml"
  when: project_root is not defined 

- name: Start Container
  hosts: "{{ ('reachable' not in groups and 'unreachable' not in groups) | ternary('all', 'reachable') }}"
  strategy: free
  gather_facts: false
  tasks:
    - name: Start Container
      ansible.builtin.shell:
        cmd: docker compose up -d
        chdir: "{{ data_root }}"
      become: true