---
assets:
  vars:
    tarfile: arduino.tar
    controller_tar: controller.tar
    mqtt_broker: 192.168.1.100
    serial_port: /dev/ttyACM0
    interface: eth0
    username: ubuntu
    pw: bellavr23
    sync_clocks: true
    cleanup: true
  hosts:
    ############################################################################################################
    ######################################### R A S P B E R R Y  P I S #########################################
    ############################################################################################################
    CONTROLLER:
      ansible_host: 192.168.1.100
      ansible_user: "{{ username }}"
      ansible_ssh_pass: "{{ pw }}"
      ansible_become_password: "{{ ansible_ssh_pass }}"
      data_root: /home/{{ ansible_user }}
      containers:
        - image: "{{ controller_tar }}"
          type: "controller"
        - image: "mosquitto.tar"
        - image: "nodered.tar"
    "1": #Laser building 1 - A
      ansible_host: 192.168.1.221
      ansible_user: "{{ username }}"
      ansible_ssh_pass: "{{ pw }}"
      ansible_become_password: "{{ ansible_ssh_pass }}"
      data_root: /home/{{ ansible_user }}
      containers:
        - image: "{{ tarfile }}"
      has_led_strip: true
      speedy_deploy: true

    "2": #Laser building 2 - B
      ansible_host: 192.168.1.220
      ansible_user: "{{ username }}"
      ansible_ssh_pass: "{{ pw }}"
      ansible_become_password: "{{ ansible_ssh_pass }}"
      data_root: /home/{{ ansible_user }}
      containers:
        - image: "{{ tarfile }}"
      speedy_deploy: true

    "3": #Laser building 3 - C
      ansible_host: 192.168.1.222
      ansible_user: "{{ username }}"
      ansible_ssh_pass: "{{ pw }}"
      ansible_become_password: "{{ ansible_ssh_pass }}"
      data_root: /home/{{ ansible_user }}
      containers:
        - image: "{{ tarfile }}"
      has_led_strip: true
      speedy_deploy: true

    "4": #Ball building 1 - D
      ansible_host: 192.168.1.155
      ansible_user: "{{ username }}"
      ansible_ssh_pass: "{{ pw }}"
      ansible_become_password: "{{ ansible_ssh_pass }}"
      data_root: /home/{{ ansible_user }}
      containers:
        - image: "{{ tarfile }}"
      speedy_deploy: true

    "5": #Laser building 2 - E
      ansible_host: 192.168.1.161
      ansible_user: "{{ username }}"
      ansible_ssh_pass: "{{ pw }}"
      ansible_become_password: "{{ ansible_ssh_pass }}"
      data_root: /home/{{ ansible_user }}
      containers:
        - image: "{{ tarfile }}"
      speedy_deploy: true