version: '3'
services:
  ansible-deploy:
    image: ansible-deploy:latest
    build:
      context: ../
      dockerfile: ./ansible/Dockerfile
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
    command: ansible-playbook /app/ansible/plays/start_all.yaml -i /app/ansible/inventories/court_2.yaml --limit="1,3,4"
    network_mode: "host"
    volumes:
      - ../:/app